CREATE TABLE produtos (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO TEXT,
    PRECO_UNITARIO NUMERIC(10, 2) NOT NULL,
    ESTOQUE_ATUAL INT DEFAULT 0,
    ESTOQUE_MINIMO INT DEFAULT 10,
    CATEGORIA VARCHAR(100),
    CRIADO_EM TIMESTAMPTZ DEFAULT NOW()
)

CREATE TABLE clientes (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    NOME_COMPLETO VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    CIDADE VARCHAR(100),
    ESTADO VARCHAR(50),
    CRIADO_EM TIMESTAMPTZ DEFAULT NOW()
)

CREATE TABLE VENDAS (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    CLIENTE_ID UUID REFERENCES clientes(ID),
    PRODUTO_ID UUID REFERENCES produtos(ID),
    QUANTIDADE INT NOT NULL,
    VALOR_TOTAL NUMERIC(10, 2) NOT NULL,
    data_venda TIMESTAMPTZ DEFAULT NOW()
)

CREATE TABLE previsao_estoque(
    ID SERIAL PRIMARY KEY,
    PRODUTO_ID UUID REFERENCES produtos(id),
    DATA_PREVISAO DATE NOT NULL,
    QUANTIDADE_PREVISTA INT NOT NULL,
    CONFIANCA_MODELO NUMERIC(10, 2),
    criado_em TIMESTAMPTZ DEFAULT NOW()
)

CREATE INDEX idx_vendas_data ON vendas(data_venda);
CREATE INDEX idx_vendas_produtos ON vendas(produto_id);